<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="drawing" nsURI="http://mycompany.fr/drawing/1.0" nsPrefix="drawing">
  <eClassifiers xsi:type="ecore:EClass" name="DrawingScript">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" lowerBound="1"
        upperBound="-1" eType="#//Command" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Forward" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="steps" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Turn" eSuperTypes="#//Command">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="DegreesWithingRange"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degrees" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
